# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spidermanager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spidermanager.proto',
  package='spider',
  syntax='proto3',
  serialized_pb=_b('\n\x13spidermanager.proto\x12\x06spider\" \n\x0b\x43onnRequest\x12\x11\n\tkeyswitch\x18\x01 \x01(\t\"\x1e\n\rReportRequest\x12\r\n\x05query\x18\x01 \x01(\t\",\n\tConnReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x0bReportReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x02 \x03(\t2x\n\x06Spider\x12\x36\n\nSpiderConn\x12\x13.spider.ConnRequest\x1a\x11.spider.ConnReply\"\x00\x12\x36\n\x06Report\x12\x15.spider.ReportRequest\x1a\x13.spider.ReportReply\"\x00\x62\x06proto3')
)




_CONNREQUEST = _descriptor.Descriptor(
  name='ConnRequest',
  full_name='spider.ConnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyswitch', full_name='spider.ConnRequest.keyswitch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=63,
)


_REPORTREQUEST = _descriptor.Descriptor(
  name='ReportRequest',
  full_name='spider.ReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='spider.ReportRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=95,
)


_CONNREPLY = _descriptor.Descriptor(
  name='ConnReply',
  full_name='spider.ConnReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='spider.ConnReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='spider.ConnReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=141,
)


_REPORTREPLY = _descriptor.Descriptor(
  name='ReportReply',
  full_name='spider.ReportReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='spider.ReportReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail', full_name='spider.ReportReply.detail', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['ConnRequest'] = _CONNREQUEST
DESCRIPTOR.message_types_by_name['ReportRequest'] = _REPORTREQUEST
DESCRIPTOR.message_types_by_name['ConnReply'] = _CONNREPLY
DESCRIPTOR.message_types_by_name['ReportReply'] = _REPORTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnRequest = _reflection.GeneratedProtocolMessageType('ConnRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNREQUEST,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.ConnRequest)
  ))
_sym_db.RegisterMessage(ConnRequest)

ReportRequest = _reflection.GeneratedProtocolMessageType('ReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _REPORTREQUEST,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.ReportRequest)
  ))
_sym_db.RegisterMessage(ReportRequest)

ConnReply = _reflection.GeneratedProtocolMessageType('ConnReply', (_message.Message,), dict(
  DESCRIPTOR = _CONNREPLY,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.ConnReply)
  ))
_sym_db.RegisterMessage(ConnReply)

ReportReply = _reflection.GeneratedProtocolMessageType('ReportReply', (_message.Message,), dict(
  DESCRIPTOR = _REPORTREPLY,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.ReportReply)
  ))
_sym_db.RegisterMessage(ReportReply)



_SPIDER = _descriptor.ServiceDescriptor(
  name='Spider',
  full_name='spider.Spider',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=190,
  serialized_end=310,
  methods=[
  _descriptor.MethodDescriptor(
    name='SpiderConn',
    full_name='spider.Spider.SpiderConn',
    index=0,
    containing_service=None,
    input_type=_CONNREQUEST,
    output_type=_CONNREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Report',
    full_name='spider.Spider.Report',
    index=1,
    containing_service=None,
    input_type=_REPORTREQUEST,
    output_type=_REPORTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPIDER)

DESCRIPTOR.services_by_name['Spider'] = _SPIDER

# @@protoc_insertion_point(module_scope)
