# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spidermanager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spidermanager.proto',
  package='spider',
  syntax='proto3',
  serialized_pb=_b('\n\x13spidermanager.proto\x12\x06spider\")\n\x07JobList\x12\r\n\x05jobid\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\" \n\x0b\x43onnRequest\x12\x11\n\tkeyswitch\x18\x01 \x01(\t\"\x1c\n\x0bListRequest\x12\r\n\x05query\x18\x01 \x01(\t\",\n\tConnReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\tListReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1b\n\x02jl\x18\x02 \x03(\x0b\x32\x0f.spider.JobList2w\n\x06Spider\x12\x36\n\nSpiderConn\x12\x13.spider.ConnRequest\x1a\x11.spider.ConnReply\"\x00\x12\x35\n\tTasksList\x12\x13.spider.ListRequest\x1a\x11.spider.ListReply\"\x00\x62\x06proto3')
)




_JOBLIST = _descriptor.Descriptor(
  name='JobList',
  full_name='spider.JobList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobid', full_name='spider.JobList.jobid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='spider.JobList.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=72,
)


_CONNREQUEST = _descriptor.Descriptor(
  name='ConnRequest',
  full_name='spider.ConnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyswitch', full_name='spider.ConnRequest.keyswitch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=106,
)


_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='spider.ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='spider.ListRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=136,
)


_CONNREPLY = _descriptor.Descriptor(
  name='ConnReply',
  full_name='spider.ConnReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='spider.ConnReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='spider.ConnReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=182,
)


_LISTREPLY = _descriptor.Descriptor(
  name='ListReply',
  full_name='spider.ListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='spider.ListReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jl', full_name='spider.ListReply.jl', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=240,
)

_LISTREPLY.fields_by_name['jl'].message_type = _JOBLIST
DESCRIPTOR.message_types_by_name['JobList'] = _JOBLIST
DESCRIPTOR.message_types_by_name['ConnRequest'] = _CONNREQUEST
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['ConnReply'] = _CONNREPLY
DESCRIPTOR.message_types_by_name['ListReply'] = _LISTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobList = _reflection.GeneratedProtocolMessageType('JobList', (_message.Message,), dict(
  DESCRIPTOR = _JOBLIST,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.JobList)
  ))
_sym_db.RegisterMessage(JobList)

ConnRequest = _reflection.GeneratedProtocolMessageType('ConnRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNREQUEST,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.ConnRequest)
  ))
_sym_db.RegisterMessage(ConnRequest)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTREQUEST,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.ListRequest)
  ))
_sym_db.RegisterMessage(ListRequest)

ConnReply = _reflection.GeneratedProtocolMessageType('ConnReply', (_message.Message,), dict(
  DESCRIPTOR = _CONNREPLY,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.ConnReply)
  ))
_sym_db.RegisterMessage(ConnReply)

ListReply = _reflection.GeneratedProtocolMessageType('ListReply', (_message.Message,), dict(
  DESCRIPTOR = _LISTREPLY,
  __module__ = 'spidermanager_pb2'
  # @@protoc_insertion_point(class_scope:spider.ListReply)
  ))
_sym_db.RegisterMessage(ListReply)



_SPIDER = _descriptor.ServiceDescriptor(
  name='Spider',
  full_name='spider.Spider',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=242,
  serialized_end=361,
  methods=[
  _descriptor.MethodDescriptor(
    name='SpiderConn',
    full_name='spider.Spider.SpiderConn',
    index=0,
    containing_service=None,
    input_type=_CONNREQUEST,
    output_type=_CONNREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TasksList',
    full_name='spider.Spider.TasksList',
    index=1,
    containing_service=None,
    input_type=_LISTREQUEST,
    output_type=_LISTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPIDER)

DESCRIPTOR.services_by_name['Spider'] = _SPIDER

# @@protoc_insertion_point(module_scope)
